baseURL: /
languageCode: en-US
defaultContentLanguage: en
title: Myblog
theme: hugo-theme-learn
metaDataFormat: yaml
publishDir: docs
defaultContentLanguageInSubdir: yes
params:
  author: Pengjiao
  customMermaidURL: https://unpkg.com/mermaid@8.8.0/dist/mermaid.min.js
  description: Bioinformatics analysis tips
  disableBreadcrumb: no
  disableLandingPageButton: yes
  disableMermaid: no
  disableNextPrev: no
  editURL: https://github.com/matcornic/hugo-theme-learn/edit/master/exampleSite/content/
  showVisitedLinks: yes
  titleSeparator: '::'
outputs:
  home:
    - HTML
    - RSS
    - JSON
Languages:
  en:
    landingPageName: <i class='fas fa-home'></i> Home
    landingPageURL: /en
    languageName: English
    menu:
      shortcuts:
        - identifier: ds
          name: <i class='fab fa-fw fa-github'></i> GitHub repo
          url: https://github.com/pengjiao
          weight: 10
    title: Documentation for Hugo Learn Theme
    weight: 1
  fr:
    landingPageName: <i class='fas fa-home'></i> Accueil
    landingPageURL: /fr
    languageName: Français
    menu:
      shortcuts:
        - identifier: ds
          name: <i class='fab fa-fw fa-github'></i> Repo GitHub
          url: https://github.com/pengjiao
          weight: 10
    title: Documentation du thème Hugo Learn
    weight: 2
  zh:
    landingPageName: <i class='fas fa-home'></i> 家
    landingPageURL: /zh
    languageName: 简体中文
    menu:
      shortcuts:
        - identifier: ds
          name: <i class='fab fa-fw fa-github'></i> GitHub 仓库
          url: https://github.com/pengjiao
          weight: 10
    title: Hugo 主题的 Learn 文档
    weight: 3
    


markup:
  goldmark:
    renderer:
      unsafe: true
